### PR TITLE
Fix yarn config output parsing

### LINKED ISSUE #154: Buildpack does not set yarn install --offline flag in offline build context
## What happened?
When an app has an offline mirror configured in its `.yarnrc` and that directory is present in the app source, [the buildpack should append the `--offline` flag to the set of flags for `yarn install`](https://github.com/paketo-buildpacks/yarn-install/blob/20edf8b86d9b0ef76590555ba15e1463efd6db12/install_process.go#L115).

However, when the buildpack runs in an offline environment, the command `yarn config get yarn-offline-mirror` produces log output:
```
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
/path/to/offline-mirror
```
which is not parseable as a path. The buildpack fails to find the offline directory and does not append the `--offline` flag to the `yarn install` command.

To reproduce:

1. Package the node buildpack version 0.0.10 for offline use
1. `git clone git@github.com:paketo-buildpacks/yarn-install`
1. `cd yarn-install/integration/testdata/vendored`
1. `pack build vendored --buildpack my-offline-buildpack.tgz --builder paketobuildpacks/builder:0.1.30-base --clear-cache --network=none`

Note the log output contains:
```
[builder]   Executing build process
[builder]     Running yarn install --ignore-engines --frozen-lockfile --modules-folder /layers/paketo-buildpacks_yarn-install/modules/node_modules
[builder]
```

This is missing the `--offline` flag.

## Checklist

Please confirm the following:

* [x] I have included log output.
* [ ] The log output includes an error message.
* [x] I have included steps for reproduction.

### PR DESCRIPTION
**Pull request by fg-j**
Thanks for contributing. To speed up the process of reviewing your pull request
please provide us with:

* A short explanation of the proposed change:
Fixes bug where `-offline` flag isn't added to install command when buildpack is used in offline environment.

* An explanation of the use cases your change enables:
resolves #154

Please confirm the following:
* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have added an integration test, if necessary.

### CODE REVIEW

**Review by arjun024 — CHANGES_REQUESTED** [review]
Hi @fg-j, I have a couple of change requests:
1) If this is the case, then the `vendored_test` should fail if you add a case where it tries to run the app? if so, could you add that case and have it succeed with your PR?
2) Could you add a comment to why you are doing line-by-line output parsing?

**Comment by fg-j** [comment]
@arjun024 

> If this is the case, then the vendored_test should fail if you add a case where it tries to run the app? if so, could you add that case and have it succeed with your PR?

As far as I can tell, the current buildpack succeeds both building and running the app. I can `pack build`, run the container, and curl the endpoint to get the "Hello World" output with no problems. I tried a little experiment to see how `yarn install` behaves in an offline context:

```
docker run -it -v ~/workspace/paketo-buildpacks/yarn-install/integration/testdata/vendored:/workspace/vendored --net none  node /bin/bash
root@cb64cb59b28e:/# curl google.com
curl: (6) Could not resolve host: google.com
root@cb64cb59b28e:/# cd workspace/vendored
root@cb64cb59b28e:/workspace/vendored# yarn install --ignore-engines --frozen-lockfile --modules-folder node_modules
yarn install v1.22.5
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.19s.
```

From what I can tell, neither build nor run will fail unless there are unmet dependencies in the `node_modules`.

**Comment by fg-j** [comment]
@arjun024 @thitch97 From what I can tell, [this blog post](https://classic.yarnpkg.com/blog/2016/11/24/offline-mirror/) seems to indicate that the `--offline` flag isn't required for yarn to use the offline mirror. To be honest, not sure what purpose the `--offline` flag really serves...

**Comment by arjun024** [comment]
My only reservation here is that in case of unmet dependencies, the user will get an error like `error Can't make a request in offline mode ("https://registry.yarnpkg.com/leftpad/-/leftpad-0.0.1.tgz")` regardless of if it's built with network, or without network.
@thitch97 Any thoughts - Do you think this is an intuitive enough error, or should we bring in `npm` and do an `npm ls` for the sake of better user feedback which would log something along the lines of `vendored node_modules have unmet dependencies` like [here](https://github.com/paketo-buildpacks/npm-install/blob/v0.2.3/integration/unmet_dependencies_test.go#L54).

**Comment by thitch97** [comment]
> My only reservation here is that in case of unmet dependencies, the user will get an error like `error Can't make a request in offline mode ("https://registry.yarnpkg.com/leftpad/-/leftpad-0.0.1.tgz")` regardless of if it's built with network, or without network.
> @thitch97 Any thoughts - Do you think this is an intuitive enough error, or should we bring in `npm` and do an `npm ls` for the sake of better user feedback which would log something along the lines of `vendored node_modules have unmet dependencies` like [here](https://github.com/paketo-buildpacks/npm-install/blob/v0.2.3/integration/unmet_dependencies_test.go#L54).

@arjun024 and I have come to the conclusion that though the unmet dependencies error can be a bit unintuitive, pulling `npm` in for the sake of a more helpful error message would perhaps be an even more confusing path to take. Thus, we'll create an issue to request some documentation about this error and potential troubleshooting steps.

**Review by arjun024 — APPROVED** [review]

**Pull request merged**
