### PR TITLE
Adds build specific logic

### LINKED ISSUE #314: Building react app with dev dependencies requires NODE_ENV set to development
## What happened?

* What were you attempting to do?

Trying to `pack build` a go + react app. The `package.json` contains:
```json
  "devDependencies": {
    "@types/react-dom": "^17.0.11",
    "connect-api-mocker": "^1.10.0",
    "express": "^4.17.2",
    "npm-run-all": "^4.1.5",
    "prettier": "2.5.1",
    "typescript": "^4.5.5"
  }
```

* What did you expect to happen?

Successful image build

* What was the actual behavior? Please provide log output, if possible.

```
Paketo Node Run Script Buildpack 0.3.2
  Executing build process
    Executing scripts
      Running 'yarn run build'
        yarn run v1.22.17
        $ react-scripts build
        Creating an optimized production build...
        Failed to compile.

        TS7016: Could not find a declaration file for module 'react-dom'. '/layers/paketo-buildpacks_yarn-install/modules/node_modules/react-dom/index.js' implicitly has an 'any' type.
          Try `npm i --save-dev @types/react-dom` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-dom';`
            1 | import React from "react";
          > 2 | import ReactDOM from "react-dom";
              |                      ^^^^^^^^^^^
            3 | import App from "./App";
            4 | import reportWebVitals from "./reportWebVitals";
            5 | import "bootstrap/dist/css/bootstrap.min.css";


        error Command failed with exit code 1.
        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

exit status 1
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

```
pack --version
0.23.0+git-0db2c77.build-3056
```

* What buildpacks are you using? Please include versions.

```
paketo-buildpacks/node-engine     0.12.1
paketo-buildpacks/yarn            0.6.0
paketo-buildpacks/yarn-install    0.8.0
paketo-buildpacks/node-run-script 0.3.2
paketo-buildpacks/go-dist         0.8.4
paketo-buildpacks/go-mod-vendor   0.4.0
paketo-buildpacks/go-build        0.7.0
```

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

```
sha: d953cb663464
```

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

### PR DESCRIPTION
**Pull request by ForestEckhardt**
If the modules are required at build time a separate layer will be
created that will install node_modules with the same logic as setting
NODE_ENV=development meaning all devDependencies will be available
for subsequent buildpacks to access. However only dependencies that
conform to the default or user set NODE_ENV will make it onto the final
running image.

Resolves #314

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by ForestEckhardt** [comment]
As a note similar behavior will need to be added to `npm-install`

**Comment by ForestEckhardt** [comment]
@genevieve If you would be willing to take a look at this and see if it accomplishes the behavior you are looking for that would be much appreciated.

**Comment by ryanmoran** [comment]
Looks like you have a typo in this new file, `package_manager_configurtion_manager.go`, and its test file, `package_manager_configurtion_manager_test.go`.

**Comment by genevieve** [comment]
@ForestEckhardt My buildpacks knowledge has already rusted! How could I go about testing this? Pull the image id from one of the build jobs, download it and run?

**Comment by ForestEckhardt** [comment]
@genevieve You could build it from source using the `package.sh` scripts and then point at either the tar ball or the buildpackage that was generated.

**Comment by genevieve** [comment]
Ok I:
1. cloned this repo
2. ran `./scripts/package.sh --version something`
3. changed my `project.toml` so the yarn-install uri was the path to the cnb file (from the output of #2)
4. ran `pack build` and got

```
Paketo Yarn Install Buildpack something
  Resolving installation process
    Process inputs:
      yarn.lock -> Found

    Selected default build process: 'yarn install'

  Executing build process
    Running yarn install --ignore-engines --frozen-lockfile --modules-folder /layers/paketo-buildpacks_yarn-install/modules/node_modules
      Completed in 39.532s

  Configuring build environment
    PATH -> "$PATH:/layers/paketo-buildpacks_yarn-install/modules/node_modules/.bin"

  Configuring launch environment
    PATH -> "$PATH:/layers/paketo-buildpacks_yarn-install/modules/node_modules/.bin"

  Generating SBOM for directory /layers/paketo-buildpacks_yarn-install/modules
      Completed in 26.513s

Paketo Node Run Script Buildpack 0.3.2
  Executing build process
    Executing scripts
      Running 'yarn run build'
exit status 1
        yarn run v1.22.17
        $ react-scripts build
        Creating an optimized production build...
        Failed to compile.

        TS7016: Could not find a declaration file for module 'react-dom'. '/layers/paketo-buildpacks_yarn-install/modules/node_modules/react-dom/index.js' implicitly has an 'any' type.
          Try `npm i --save-dev @types/react-dom` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-dom';`
            1 | import React from "react";
          > 2 | import ReactDOM from "react-dom";
              |                      ^^^^^^^^^^^
            3 | import App from "./App";
            4 | import reportWebVitals from "./reportWebVitals";
            5 | import "bootstrap/dist/css/bootstrap.min.css";


        error Command failed with exit code 1.
        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

**Comment by genevieve** [comment]
Ignore all of that ^, I cloned this repo but did not check out the right branch. 🤦🏻‍♀️ 

This **does** work!

**Review by ryanmoran — APPROVED** [review]

**Pull request merged**
